#!/bin/bash
time=$(($1*1000))
cpu1=$2
cpu2=$3

sudo numactl --cpunodebind=0 perf stat --timeout ${time} --cpu=${cpu1}-${cpu2} -e MEM_LOAD_L3_MISS_RETIRED.LOCAL_DRAM,MEM_LOAD_RETIRED.LOCAL_PMM,MEM_LOAD_L3_MISS_RETIRED.REMOTE_DRAM,MEM_LOAD_L3_MISS_RETIRED.REMOTE_PMM
#sudo perf stat --timeout ${time} -a -e MEM_LOAD_L3_MISS_RETIRED.LOCAL_DRAM,MEM_LOAD_RETIRED.LOCAL_PMM,MEM_LOAD_L3_MISS_RETIRED.REMOTE_DRAM,MEM_LOAD_L3_MISS_RETIRED.REMOTE_PMM
