#!/bin/bash

watch -n1 "
cat /proc/vmstat | \
	grep -E 'pgmigrate|pgexchange|pgactivate_deferred|pgreference|nr_page_skipped|pgexchanged_skip'; \
cat /proc/zoneinfo | \
	grep -E 'hmem_migrate_dst|hmem_migrate_fail_dst' | paste - -
cat /proc/zoneinfo | \
	grep -E 'hmem_demote_dst|hmem_demote_src' | paste - -
cat /proc/zoneinfo | \
	grep -E 'nr_deferred|nr_exchanged|isolated_anon' | paste - - -
cat /proc/zoneinfo | \
	grep -E 'nr_cold'
ps -aux | \
	grep -E 'kexchanged' | grep -v grep
"
